name: gemini_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  #network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  logger: ^1.1.0

  #file
  image_picker: ^1.0.7
  video_player: ^2.8.6
  cached_network_image: ^3.2.2

  #animation
  page_transition: ^2.1.0

  #getx
  get: ^4.6.6

  #speech_to_text:
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  #databse
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #path_provider:
  path_provider: ^2.1.2


  #animations:
  lottie:

  #shake
  shake: ^2.2.0
  flutter_sensors:

  #bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5


  #webview
  flutter_linkify: ^6.0.0
  url_launcher: ^6.0.20
  webview_flutter: ^4.8.0

  #progress barcode_widget:
  linear_progress_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
